### PR TITLE
Re-dds amazon SDK dependency and marks as optional

### PR DESCRIPTION
**Pull request by felipecsl**

### CODE REVIEW

**Comment by nwadams** [comment]
I think we should make this an add on module and not part of the main lib.

**Comment by felipecsl** [comment]
If it looks good to you guys, I'll push it to central and test it on an external project by making sure it doesn't require Amazon. I already tested on the sample app by deploying to my maven local repo and confirmed it worked fine without the amazon aar file

**Comment by felipecsl** [comment]
@nwadams I agree, once we add the amazon logic we could add that into a submodule. Right now we don't even have any code that uses it, so it might not even make sense to merge this.

**Comment by nwadams** [comment]
yeah. I agree lets not add the amazon dependency at all until the amazon version of the lib is ready.

**Pull request closed without merging**
