### PR TITLE
Prevent crash on Android M new permission model

### PR DESCRIPTION
**Pull request by felipecsl**
Native Google Maps needs `WRITE_EXTERNAL_STORAGE` permission on Android M, so we should check for that as well before assuming that it is supported.
This prevents AirMapView from crashing on M.

@petzel @nwadams

### CODE REVIEW

**Comment by felipecsl** [comment]
ugh Travis doesn't support android 23 yet...

**Comment by rafaeltoledo** [comment]
Update your `.travis.yml` and it should work :)

**Comment by felipecsl** [comment]
oh sweet. for some reason I assumed travis was not gonna work with api 23. all clear now. thanks Rafael!

**Comment by amoljain** [comment]
lgtm.

**Pull request merged**
