### PR TITLE
Don't force location permissions

### PR DESCRIPTION
**Pull request by nwadams**
Don't force enabling location permissions when loading map. First commit needs to be taken out once the PR for it is merged. 

Resolves https://github.com/airbnb/AirMapView/issues/97

@felipecsl @petzel @gpeal

### CODE REVIEW

**Comment by forrestbice** [comment]
Thanks @nwadams! Do you know when a release will be cut with this fix included? CC @felipecsl

**Comment by felipecsl** [comment]
@forrestbice you can grab the snapshot version right now with `1.4.1-SNAPSHOT`

**Comment by forrestbice** [comment]
Awesome! Thanks @felipecsl

**Comment by forrestbice** [comment]
@nwadams @felipecsl just opened a very similar issue https://github.com/airbnb/AirMapView/issues/103 and a PR https://github.com/airbnb/AirMapView/pull/104 which will hopefully address the issue. Would greatly appreciate a quick look

**Pull request merged**
