### PR TITLE
Prepare for the 1.6 release

### PR DESCRIPTION
**Pull request by sushichris880**
## Change summary:
Update assets for a 1.6 release

@elihart @felipecsl

### CODE REVIEW

**Comment by felipecsl** [comment]
@sushichris880 this is version 1.6.0, instead of 1.7, right?

**Comment by sushichris880** [comment]
@felipecsl Oh right, sorry just named the PR incorrectly

**Comment by felipecsl** [comment]
Dont forget to add the [release](https://github.com/airbnb/AirMapView/releases) when its uploaded!

**Comment by sushichris880** [comment]
awesome thanks @felipecsl! mind merging for me?  cc @elihart

**Comment by felipecsl** [comment]
@sushichris880 we should only merge this once v1.6.0 has been already uploaded and is live here http://repo1.maven.org/maven2/com/airbnb/android/airmapview/
Otherwise people will get confused by looking at the readme if the version doesnt yet exists.

**Pull request merged**
